Try to download ImageMagick. If that fails, show an error and stop the build.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -20,7 +20,10 @@ if [ ! -f $CACHE_FILE ]; then
   IMAGE_MAGICK_URL="https://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
 
   echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
-  wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
+  if ! wget $IMAGE_MAGICK_URL -P $BUILD_DIR; then
+    echo "Error: Failed to download ImageMagick archive." | indent
+    exit 1
+  fi
 
   echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
   if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
